/**
 * Emits the marketing site's inline organism `<defs>` plus per-alias
 * family/hue assignments, generated by the real `organisms.ts` pipeline so
 * the site shows exactly what those coves would grow in the app.
 * Run: bun run scripts/emit-site-organisms.ts
 */
import {
  CORAL_PATHS,
  FAMILIES,
  generateFamily,
  organismFor,
  type OrganismPath,
} from "../src/components/organisms";
import { spaceColor } from "../src/components/spaceColor";

function pathsToMarkup(paths: readonly OrganismPath[]): string {
  return paths
    .map((p) =>
      p.stroke !== undefined
        ? `<path d="${p.d}" fill="none" stroke="currentColor" stroke-width="${p.stroke}" stroke-linecap="round" stroke-linejoin="round"/>`
        : `<path d="${p.d}" fill="currentColor"${p.evenodd ? ' fill-rule="evenodd"' : ""}/>`,
    )
    .join("");
}

/** One hand-picked seed per family for the seabed strip. */
const STRIP_SEEDS: Record<string, number> = {
  sunAnemone: 1, tubes: 5, staghorn: 2, brain: 8, flower: 1, scallop: 2,
  spiral: 3, bubbles: 1, seagrass: 2, shell: 5, nudibranch: 3,
};

console.log(`<g id="o-coral">${pathsToMarkup(CORAL_PATHS)}</g>`);
for (const fam of FAMILIES) {
  const org = generateFamily(fam, STRIP_SEEDS[fam]!);
  console.log(`<g id="o-${fam}">${pathsToMarkup(org.paths)}</g>`);
}

const HUE_VARS: Record<string, string> = {
  "#f59e0b": "--amber", "#6366f1": "--indigo", "#ec4899": "--pink",
  "#0284c7": "--sky", "#84cc16": "--lime", "#8b5cf6": "--violet",
  "#f97316": "--orange", "#0d9488": "--seafoam",
};

console.log("\n# circle aliases (family / hue var / def markup):");
for (const alias of ["household", "schoolrun", "accountant", "trip"]) {
  const org = organismFor(alias);
  const hue = spaceColor(alias);
  console.log(`## ${alias}: ${org.family} ${HUE_VARS[hue.base] ?? hue.base}`);
  console.log(`<g id="o-cove-${alias}">${pathsToMarkup(org.paths)}</g>`);
}
