"""initial schema

Revision ID: 0f1d29c16349
Revises: 
Create Date: 2026-08-05 17:12:55.524072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f1d29c16349'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('spaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('PERSONAL', 'HOUSEHOLD', name='spacekind'), nullable=False),
    sa.Column('owner_person_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_person_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('memberships',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'space_id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'path')
    )
    op.create_index(op.f('ix_pages_space_id'), 'pages', ['space_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='attachmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_attachments_space_id'), 'attachments', ['space_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('dest_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_page_id'), 'revisions', ['page_id'], unique=False)
    # ### end Alembic commands ###

    # NULLIF(..., '') matters here, not just current_setting(..., true) on its
    # own: a session where app.person_id was never touched returns NULL from
    # current_setting and denies as intended, but resolve_space's principal
    # -clearing path (and these very policies' own tests) instead does
    # set_config('app.person_id', '', true) -- a defined empty string, not an
    # absence -- and ''::uuid raises rather than comparing false. NULLIF folds
    # both cases to the same NULL, so both deny the same way.
    for table in ("pages", "attachments"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_member ON {table}
            USING (space_id IN (
                SELECT space_id FROM memberships
                WHERE person_id = NULLIF(current_setting('app.person_id', true), '')::uuid))
            WITH CHECK (space_id IN (
                SELECT space_id FROM memberships
                WHERE person_id = NULLIF(current_setting('app.person_id', true), '')::uuid))
            """
        )
    op.execute("ALTER TABLE revisions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE revisions FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY revisions_member ON revisions
        USING (page_id IN (
            SELECT p.id FROM pages p
            JOIN memberships m ON m.space_id = p.space_id
            WHERE m.person_id = NULLIF(current_setting('app.person_id', true), '')::uuid))
        WITH CHECK (page_id IN (
            SELECT p.id FROM pages p
            JOIN memberships m ON m.space_id = p.space_id
            WHERE m.person_id = NULLIF(current_setting('app.person_id', true), '')::uuid))
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS revisions_member ON revisions")
    op.execute("ALTER TABLE revisions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE revisions DISABLE ROW LEVEL SECURITY")
    for table in ("pages", "attachments"):
        op.execute(f"DROP POLICY IF EXISTS {table}_member ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_page_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_attachments_space_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_pages_space_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_table('memberships')
    op.drop_table('spaces')
    op.drop_table('persons')
    # ### end Alembic commands ###
