"""promotions.section_text for section shares

Revision ID: 131e9ad66476
Revises: d8567d9ee6dc
Create Date: 2026-08-06 09:57:31.600324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131e9ad66476'
down_revision: Union[str, Sequence[str], None] = 'd8567d9ee6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('section_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'section_text')
    # ### end Alembic commands ###
